///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : fusiondata.h
/// SOFTWARE COMPONENT NAME           : FusionData
/// GENERATED DATE                    : 2024-11-13 13:00:52
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#ifndef PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_FUSIONDATA_H
#define PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_FUSIONDATA_H
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// INCLUSION HEADER FILES
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "deepracer/service/fusiondata/svfusiondata_skeleton.h"
 
#include "ara/log/logger.h"
 
#include <mutex>
#include <thread>
 
namespace deepracer
{
namespace service
{
namespace fusiondata
{
namespace skeleton
{
 
class SvFusionDataSkeletonImpl : public SvFusionDataSkeleton
{
public:
    /// @brief Constructor
    SvFusionDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode = ara::com::MethodCallProcessingMode::kEvent);
    
    
    
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    
};
 
} /// namespace skeleton
} /// namespace fusiondata
} /// namespace service
} /// namespace deepracer

namespace sensorfusion
{
namespace aa
{
namespace port
{
 
class FusionData
{
public:
    /// @brief Constructor
    FusionData();
    
    /// @brief Destructor
    ~FusionData();
    
    /// @brief Start port
    void Start();
    
    /// @brief Terminate port
    void Terminate();
    
    /// @brief Write event data to buffer, FEvent
    void WriteDataFEvent(const deepracer::service::fusiondata::skeleton::events::FEvent::SampleType& data);
     
    /// @brief Send event cyclic from buffer data, FEvent
    void SendEventFEventCyclic();
     
    /// @brief Send event directly from buffer data, FEvent
    void SendEventFEventTriggered();
     
    /// @brief Send event directly with argument, FEvent
    void SendEventFEventTriggered(const deepracer::service::fusiondata::skeleton::events::FEvent::SampleType& data);
     
private:
    /// @brief Logger for this port
    ara::log::Logger& m_logger;
    
    /// @brief Flag of port status
    bool m_running;
    
    /// @brief Mutex for this port
    std::mutex m_mutex;
    
    /// @brief AUTOSAR Port Interface
    std::shared_ptr<deepracer::service::fusiondata::skeleton::SvFusionDataSkeletonImpl> m_interface;
    
    /// @brief Data for event, FEvent
    deepracer::service::fusiondata::skeleton::events::FEvent::SampleType m_FEventData;
};
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
#endif /// PARA_AA_GEN_SOFTWARE_COMPONENT_PPORT_SENSORFUSION_AA_FUSIONDATA_H