///////////////////////////////////////////////////////////////////////////////////////////////////////////
///                                                                                                        
/// Copyright, 2021 PopcornSAR Co., Ltd. All rights reserved.                                              
/// This software is copyright protected and proprietary to PopcornSAR Co., Ltd.                           
/// PopcornSAR Co., Ltd. grants to you only those rights as set out in the license conditions.             
///                                                                                                        
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// AUTOSAR VERSION                   : R20-11
/// GENERATED BY                      : PARA, Adaptive Application Generator
///////////////////////////////////////////////////////////////////////////////////////////////////////////
/// GENERATED FILE NAME               : fusiondata.cpp
/// SOFTWARE COMPONENT NAME           : FusionData
/// GENERATED DATE                    : 2024-11-13 13:00:52
///////////////////////////////////////////////////////////////////////////////////////////////////////////
#include "sensorfusion/aa/port/fusiondata.h"
 
namespace deepracer
{
namespace service
{
namespace fusiondata
{
namespace skeleton
{
 
SvFusionDataSkeletonImpl::SvFusionDataSkeletonImpl(ara::core::InstanceSpecifier instanceSpec, ara::com::MethodCallProcessingMode mode)
    : SvFusionDataSkeleton(instanceSpec, mode)
    , m_logger(ara::log::CreateLogger("SSFU", "PORT", ara::log::LogLevel::kVerbose))
{
}
 
} /// namespace skeleton
} /// namespace fusiondata
} /// namespace service
} /// namespace deepracer

namespace sensorfusion
{
namespace aa
{
namespace port
{
 
FusionData::FusionData()
    : m_logger(ara::log::CreateLogger("SSFU", "PORT", ara::log::LogLevel::kVerbose))
    , m_running{false}
    , m_FEventData{{{0U, 0U, 0U}, {0U, 0U, 0U}, {0U, 0U, 0U}}, {0.0f, 0.0f, 0.0f}, 0LL}
{
}
 
FusionData::~FusionData()
{
}
 
void FusionData::Start()
{
    m_logger.LogVerbose() << "FusionData::Start";
    
    // construct skeleton
    ara::core::InstanceSpecifier specifier{"SensorFusion/AA/FusionData"};
    m_interface = std::make_shared<deepracer::service::fusiondata::skeleton::SvFusionDataSkeletonImpl>(specifier);
    
    // offer service
    auto offer = m_interface->OfferService();
    if (offer.HasValue())
    {
        m_running = true;
        m_logger.LogVerbose() << "FusionData::Start::OfferService";
    }
    else
    {
        m_running = false;
        m_logger.LogError() << "FusionData::Start::OfferService::" << offer.Error().Message();
    }
}
 
void FusionData::Terminate()
{
    m_logger.LogVerbose() << "FusionData::Terminate";
    
    // stop port
    m_running = false;
    
    // stop offer service
    m_interface->StopOfferService();
    m_logger.LogVerbose() << "FusionData::Terminate::StopOfferService";
}
 
void FusionData::WriteDataFEvent(const deepracer::service::fusiondata::skeleton::events::FEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_FEventData = data;
}
 
void FusionData::SendEventFEventCyclic()
{
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_mutex);
            auto send = m_interface->FEvent.Send(m_FEventData);
            if (send.HasValue())
            {
                m_logger.LogVerbose() << "FusionData::SendEventFEventCyclic::Send";
            }
            else
            {
                m_logger.LogError() << "FusionData::SendEventFEventCyclic::Send::" << send.Error().Message();
            }
        }
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
 
void FusionData::SendEventFEventTriggered()
{
    std::lock_guard<std::mutex> lock(m_mutex);
    auto send = m_interface->FEvent.Send(m_FEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "FusionData::SendEventFEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "FusionData::SendEventFEventTriggered::Send::" << send.Error().Message();
    }
}
 
void FusionData::SendEventFEventTriggered(const deepracer::service::fusiondata::skeleton::events::FEvent::SampleType& data)
{
    std::lock_guard<std::mutex> lock(m_mutex);
    m_FEventData = data;
    auto send = m_interface->FEvent.Send(m_FEventData);
    if (send.HasValue())
    {
        m_logger.LogVerbose() << "FusionData::SendEventFEventTriggered::Send";
    }
    else
    {
        m_logger.LogError() << "FusionData::SendEventFEventTriggered::Send::" << send.Error().Message();
    }
}
 
} /// namespace port
} /// namespace aa
} /// namespace sensorfusion
 
/// EOF